---
title: "Week9Assignment"
author: "John Navarro"
date: "December 3, 2016"
output: pdf_document
---

#Part 1 Data
```{r}
Project.Data<-read.csv(file="C:/Users/JohntheGreat/Documents/MSCA/StatisticalAnalysis/Week9/Assignments/PCA_ExampleData.csv",header=TRUE,sep=",")
 Project.Data[1:10,]
#Separate the first row of Project.Data
Data.Levels<-as.numeric(Project.Data[1,])
Project.Data<-Project.Data[-1,]
head(Project.Data)
#Plot the data
matplot(Project.Data,type="l")
```
#Part 2 PCA

```{r}
Project.Data.PCA <- princomp(Project.Data)
names(Project.Data.PCA)
#Plot Loadings
matplot(Data.Levels,Project.Data.PCA$loadings[,1:3],type="l",lty=c(1,2,3),lwd=2,xaxt="n", xlab="Data.Levels",ylab="Loadings",ylim=c(-0.6,0.4),col=c("black","red","green"))
abline(h=0)
#axis(1, -10:10,labels=colnames(swissPredictors))
axis(1, -10:10)
#Plot Factors
matplot(Project.Data.PCA$scores,type="l",lty=c(1,2,3),lwd=c(1,2,5),lend=2,ylim=c(-900,900),col=c("black","red","green"))
#Plot Variances
barplot(Project.Data.PCA$sdev^2, ylab = "Variances")
Project.Data.PCA$sdev^2
Project.Data.PCA$sdev^2/sum(Project.Data.PCA$sdev^2)
```
Estimate PCA using manual calculation with eigen(). For this recall the steps on slide 16 of the lecture notes.


```{r}
#create centered matrix
centered.Project.Data <- scale(Project.Data, scale = FALSE)
cov.matrix <- cov(centered.Project.Data)
eigen.decomp <- eigen(cov.matrix)

```
Calculate 3 factor loadings using PCA and using manual method based on eigen-decomposition. Combine them in one matrix  Project.Data.PCA.by.eigen.Loadings and compare
```{r}
#eigen columns
Project.Data.PCA.Eigen.Loadings1 <- eigen.decomp$vectors[,1:3]

#bind with PCA columns
Project.Data.PCA.Eigen.Loadings1 <- cbind(Project.Data.PCA.Eigen.Loadings1,Project.Data.PCA$loadings[,1:3])

#rename the columns
colnames(Project.Data.PCA.Eigen.Loadings1) <- c("L1.eigen", "L2.eigen", "L3.eigen", "L1.PCA", "L2.PCA", "L3.PCA")
head(Project.Data.PCA.Eigen.Loadings1)
```
